name: Update API

on: 
  push: 
    branches:
      - main
      - testing
    paths: 
      - 'infra/**'

jobs: 
  build-infra: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with: 
          terraform_version: 1.9.7 

      - name: Configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWSAKIDB }}
          aws-secret-access-key: ${{ secrets.AWSSAKB }}
          aws-region: ${{ secrets.AWSRG }}
      
      - name: Initialize Terraform 
        run: terraform init -backend-config="bucket=${{ secrets.TF_BUCKET}}" -backend-config="key=${{ secrets.TF_KEY }}"  -backend-config="region=${{ secrets.AWSRG }}"
        working-directory: infra

      - name: Configure region 
        run: echo "TF_VAR_AWSRG=${{ secrets.AWSRG }}" >> $GITHUB_ENV
        working-directory: infra

      - name: Terraform plan 
        run: terraform plan -out=plan.tfplan
        working-directory: infra

      - name: Terraform apply
        run: terraform apply plan.tfplan
        working-directory: infra
  
  test: 
    runs-on: ubuntu-latest
    needs: [build-infra]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: '21'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress
        env:
          BASE_URL: 'https://ylana-ong.com/'
          CYPRESS_API: ${{ secrets.CYPRESS_API }}
        run: npx cypress run
        
      